project:
  type: website
  output-dir: docs

website:
  title: '<img src="media/SRKLogo.svg" alt="SRK Consulting" style="height: 30px;">'
  navbar:
    right:
      - text: Span
        href: StartCodingToday_Span.qmd
      - text: Eng
        href: StartCodingToday_Eng.qmd

format:
  html:
    toc: true 
    css: styles/srk.css  # Optional: Link to a custom CSS file

